version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  sam: circleci/aws-sam-serverless@3.2.0
workflows:
  test_and_deploy:

    jobs:
      - zip_script
      - build_and_package:
          requires:
            - zip_script
          context: sa-jc-aws-creds-context

# Deploy test 
jobs:
  # Create zip of script 
  zip_script:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip3 install boto3 --target=./AWS/DirectoryInsights
      - run: sudo pip3 install requests --target=./AWS/DirectoryInsights
      #- run: ls ./AWS/DirectoryInsights
      - run: zip -r ./AWS/DirectoryInsights/get-jcdirectoryinsights.zip ./AWS/DirectoryInsights 
      - run: ls ./AWS/DirectoryInsights/
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_and_package:
    executor: sam/default
    steps:
      - attach_workspace:
          at: .
      - sam/install
      - run:
          command: sam package --template-file ./AWS/DirectoryInsights/serverless.yaml --output-template-file ./AWS/DirectoryInsights/packaged.yaml --s3-bucket jc-circleci-test-bucket


