version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  sam: circleci/aws-sam-serverless@3.2.0
workflows:
  test_and_deploy:

    jobs:
      - zip_script
      - sam/deploy:
          requires:
            - zip_script
          context: sa-jc-aws-creds-context
          name: deploy-staging
          s3-bucket: jc-circleci-test-bucket
          stack-name: jc-ken-circleci-test-stack
          template: './AWS/DirectoryInsights/serverless.yaml'
      

# Deploy test 
jobs:
  # Create zip of script 
  zip_script:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip3 install boto3 --target=./AWS/DirectoryInsights
      - run: sudo pip3 install requests --target=./AWS/DirectoryInsights
      #- run: ls ./AWS/DirectoryInsights
      - run: zip -r ./AWS/DirectoryInsights/get-jcdirectoryinsights.zip ./AWS/DirectoryInsights 
      - run: ls ./AWS/DirectoryInsights/
      - persist_to_workspace:
          root: .
          paths:
            - .
   